### ISSUE TITLE
Crash on OSX in release

### ISSUE THREAD

**Issue by wolfviking0** [IMQS/uberlog#2]
Hi,

I am playing with uberlog and It's really nice how its work, but for some reason I am facing an issue on OSX.

Windows and Linux work fine in debug and release but when I build the osx version in release I have a crash inside uberlog_tsf::fmt_core.

Because its in release its difficult to find the exact error but after adding a lot for printf the crash seems to come from the function format_string inside tsf.cpp line 75.

The access to s[i] crash, the pointer is not null but it seems to be incorrect.
Any idea why that's kind of issue happen on osx and only in release mode ?

Thanks

**Comment by bmharper** [comment]
That's quite strange - the code assumes that 's' is null terminated, and it does check every byte for zero. So perhaps it's memory corruption that happens earlier.

I don't have a Mac with me in the office right now, but I'll check it out when I get home tonight.

Can you share the precise log message that causes the crash?

**Comment by wolfviking0** [comment]
Hi @bmharper, indeed it's really strange, I agree it could be corrupted memory but the code it's quite straight forward. 
In fact the code it's really simple but it's using flatbuffers and I don't know if it could be related to that. 
I was able to print the filename with the same log system just before calling the function 'LoadJSONFile'.

FYI, I just submit a pull request for small fixes on OSX.

    tempate <typename T>
    const T * loadJSONFile(const char * filename, flatbuffers::Parser * parser)
    {
        std::lock_guard<std::mutex> guard(_mutex);
        std::string jsonfile;
        bool ok = flatbuffers::LoadFile(filename, false, &jsonfile);
        if (!ok)
        {
            LOG_ERROR("FBSUtility::loadJSONFile() : Failed to load file '%s'", filename);
            return nullptr;
        }
        
        ...
    }

where LOG_ERROR is : 

    // GLOBAL
    uberlog::Logger Log;
    // MACRO
    #define LOG_ERROR(...)      Log.Error(__VA_ARGS__);

**Comment by wolfviking0** [comment]
Hi @bmharper, I found something using CMake for building the project, I build using RelWithDebInfo and I found something interesting for some reason the filename seems to be an empty string, and that give a crash in uberlog. It could be nice to have a security in uberlog to avoid such issue. But I have something incorrect in my code because the filename should not be null.

**Comment by bmharper** [comment]
Thanks - PR looks good, but I just want to see if there is a more efficient way of checking for parent process death on OSX, so that we don't have to enumerate all processes. And will add a check to Open() for nullptr or empty string.

Any chance you can get your bug to reproduce as a test case inside test.cpp?

I've tried copying your code in, but I can't manage to produce a crash.

**Comment by wolfviking0** [comment]
For the pull request, I finally used the same function of Linux getppid, it seems to be working fine, and that remove the enumerate.
For the issue I try to reduce to a small test case but then the issue it’s not happening :(

**Comment by bmharper** [comment]
What might help catch the issue is to try compiling your code (and the uberlog code) with `-fsanitize=address` (https://clang.llvm.org/docs/AddressSanitizer.html)

**Comment by wolfviking0** [comment]
HI @bmharper I am trying with fsanitize, and I have some error related to uberlog:

==55645==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x000107a09877 at pc 0x0001009a1791 bp 0x7ffeefbfe550 sp 0x7ffeefbfdd00
WRITE of size 10 at 0x000107a09877 thread T0
uberlog writer [/Users/anthony.liot/Library/Caches/Vault/logs/VaultLog.log, 5 MB max size, 3 archives] is starting
atos(55652,0x100368380) malloc: enabling scribbling to detect mods to free blocks
    #0 0x1009a1790 in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x52790)
    #1 0x10018d5d5 in uberlog::internal::TimeKeeper::Format(char*) uberlog.cpp:659
    #2 0x1001934af in uberlog::Logger::LogDefaultFormat_Phase2(uberlog::Level, bool, uberlog_tsf::StrLenPair, bool) uberlog.cpp:1099

I am currently looking to that.

**Comment by wolfviking0** [comment]
@bmharper I fix my code the issue was a mistake in some buffer size, and I was corrupting the memory.
Thanks for you help.
